const GET_NEW_ALBUMS_LIST = 'GET_NEW_ALBUMS_LIST';
const SEARCH_ALBUMS = 'SEARCH_ALBUMS';
const ENTER_LOADING = 'ENTER_LOADING';
const SEARCH_LOADING = 'SEARCH_LOADING';
export { GET_NEW_ALBUMS_LIST, SEARCH_ALBUMS, ENTER_LOADING, SEARCH_LOADING };
